### ISSUE TITLE
Error with Get Tracks - API change /v3/motor_data/track ? 

### ISSUE THREAD

**Issue by dathosim** [BlueAndi/niu-cloud-cli#1]
I like your project !
I would like to have data of my Niu Scooter to integrate in Home Assistant 
Your CLI is perfect but only on error on get-tracks 
After many research, i think API have been change : /v3/motor_data/track/ respond an error...
Could you help me to find the new API point please, just the end point.
Thanks a lot !

**Comment by BlueAndi** [comment]
Thanks.
I will check the endpoint, but I guess I must try to reverseengineer it from the latest niu app.

**Comment by BlueAndi** [comment]
It looks like this is the new endpoint ```/v5/track/list/v2``` according to niu app 4.6.2 but I get a 500 (internal server error).
Have to think about ...

@dathosim
Can you check this endpoint too? Currently my NIU is unpowered and this may influence the request.

**Comment by dathosim** [comment]
Thanks a lot ! 
I check this endpoint too with node-red (i have a flow node red to test API efficient with other endpoint)
But i get an error too.
"Json parse error" if i attempt to parse the outpout
And object empty if i don't..

I inject **sn**, **token**, **pagesize** and **index** (like old endpoint) 
You think is a GET or POST request ? 

But i can't reverseengineer because i have iOS app 
NB : I try too : /v3/ track/list/V2 or /v5/track/list etc...

**Comment by BlueAndi** [comment]
Its a POST request, similar to the others.
The parameters are the same as for ```/v3/motor_data/track```.
I asked one in the [forum](https://www.elektroroller-forum.de/viewforum.php?f=63) whether he could support with a wireshark trace. Waiting for reponse now.

**Comment by dathosim** [comment]
Any news ? 
How to use the new track endpoint please ?

**Comment by BlueAndi** [comment]
Unfortunately I didn't receive any response yet. Are you able to create a trace with e.g. https://mitmproxy.org ?
I will do, but can not promise that it will be in the next week.

**Comment by dathosim** [comment]
Yes ! i have created a trace with mitmproxy ! (great tool)

`
POST https://app-api-fk.niu.com/v5/track/list/v2                 ← 200 OK application/json 5.02k 204ms

Host:             app-api-fk.niu.com            
Content-Type:     application/json 
Accept-Encoding:  gzip, deflate,            
Connection:       keep-alive                           
Accept:           */*                          
User-Agent:       manager/4.6.2 (iPhone; iOS 14.4; Scale/3.00);deviceName=iPhone;timezone=Europe/Paris;model=iPhone 11 Pro;lang=fr-FR;ostype=iOS;clientIdentifier=Overseas            
Accept-Language:  fr-FR;q=1, en-GB;q=0.9, en-FR;q=0.8, ja-JP;q=0.7                                                                                                                                  
Content-Length:   412                             
token:            1YjQzYmVhYWFjMmY2ODIwMjhkM2Q0ZTMifQ....RndrQ      

JSON                                                                                                                                                {
    "index": "0",
    "pagesize": 10,
    "sn": "NASGXXXXXXXX",
    "token": "eyJhbGciOiJIUzUxMiIsImtpZ...."
}
`
In this new version, the token must be send in the json ;-)
I progress...

**Comment by BlueAndi** [comment]
Sounds good. Can you share a longer trace and replacing your token with "xxx"? Its interesting which kind of requests are done during startup and till joining the track list. In your shown snapshot there is a token element in the header too, but with a different id?

**Comment by BlueAndi** [comment]
I updated today the code to reflect this change. Anyway it responses with a "authenticaton failed" in chinese.

**Comment by BlueAndi** [comment]
@dathosim Please verify, it should work with latest changes. Note, update the submodule, as it contains the important change.

**Comment by dathosim** [comment]
Great job ! it works perfectly !
It was very important to specify User-Agent in our request to API
Niu API attempt a string start by "manager/vX.X.X (YYY)" and end by "clientIdentifier=ZZZ" 
If you want, you can reduce and anonymise ;-) the User-Agent string to : 'manager/1.0.0 (identifier);clientIdentifier=identifier'
(because I see my user-agent trace by mitmproxy in your code)

**Comment by BlueAndi** [comment]
I tried several times to anonymize it, but the the NIU cloud expects always a correct setup.
XXX = NIU app version (they cloud may behave different, depended on this version)
The clientIdentifier must be "overseas" and is not unique for your client. It is the same for all in europe.
I tried several other platforms, devices,etc. as well, but didn't get any working setup.
Therefore I used the one from your trace ;-) and removed only the stuff, which is not necessary.

Did you try your proposed user-agent string? Its not working for me.

**Comment by dathosim** [comment]
Yes I have try with this string.
I tested not with your code but with Node-Red and this entries : 
```
msg.payload = {
    "index": "0",
    "pagesize": 10,
    "sn": "NASXXXXXX",
    "token": "eyJhbGciOiJIUzUxMiIsIm...."
    
};
msg.headers = {};
msg.headers['token'] = 'eyJhbGciOiJIUzUxMiIsIm...';
msg.headers['User-Agent'] = 'manager/1.0.0 (identifier);clientIdentifier=identifier';
return msg;
```
Without accept-language
On this API point : https://app-api-fk.niu.com/v5/track/list/v2
And it's working for me

**Comment by BlueAndi** [comment]
Hmm ... I tried exactly your example and it doesn't work for me (removing accept-language).
Can you show me the real HTTP header, which is sent?

**Comment by dathosim** [comment]
Accept-Language: "en-US"
User-Agent: "manager/1.0.0 (identifier);clientIdentifier=identifier"
token: "eyJhbGciOiJIU.....S1kIw"
