### ISSUE TITLE
npm install fails on "md5@^2.3.0' is not in this registry

### ISSUE THREAD

**Issue by tinythomasffm** [BlueAndi/niu-cloud-cli#11]
when trying to rebuild my container image:

$ npm install
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/md5 - Not found
npm error 404
npm error 404  'md5@^2.3.0' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/thomas/.npm/_logs/2024-12-08T18_33_00_966Z-debug-0.log

**Comment by BlueAndi** [comment]
But its there: https://www.npmjs.com/package/md5?activeTab=readme
And the v2.3.0 is still the latest one: https://github.com/pvorb/node-md5/blob/master/package.json
:-?

**Comment by tinythomasffm** [comment]
looks like this was a temporary error. npmjs.org returns the package now. Never mind.
